pem_meta:
    resource: "@PemMetaBundle/Controller/"
    type:     annotation
    prefix:   /

pem_book:
    resource: "@PemProjectBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
